# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$container\
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$character\
"""

[container]
symbol = "ğŸ³"
format = "[$symbol]($style)"

[line_break]
disabled = true

[git_branch]
symbol = ""
format = '[\($symbol$branch(:$remote_branch)\)]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"

[character]
format = "$symbol "
