[colors]
draw_bold_text_with_bright_colors = false

[window]
decorations = "None"

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]
# import = [
#     "~/.config/alacritty/themes/themes/gruvbox_material_hard_light.toml"
# ]

[font.bold]
family = "CommitMono"
style = "Bold"

[font.bold_italic]
family = "CommitMono"
style = "Bold Italic"

[font.italic]
family = "CommitMono"
style = "Italic"

[font.normal]
family = "CommitMono"
style = "Regular"
